apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "techtrends.fullname" . }}
  labels:
    app: {{ include "techtrends.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "techtrends.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "techtrends.name" . }}
    spec:
      containers:
        - name: {{ include "techtrends.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
{{ toYaml .Values.resources | indent 12 }}
      imagePullSecrets:
        - name: regcred
